{{- range $configmap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with $configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with $configmap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
