{{- if .Values.hybridConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-hybrid
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  # Regular environment variables
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

  # Secret references (these will be injected by external-secrets)
  {{- if .Values.hybridConfig.secretRefs }}
  {{- range $key, $value := .Values.hybridConfig.secretRefs }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}
{{- end -}}
